<a id='section1'></a>
# Instalación de la librería
Ejecutar el siguiente comando en el CMD para instalar la librería de python.

In [1]:
#pip install pydataxm

<a id='section2'></a>
# Importación de librerías

In [2]:
from pydataxm.pydatasimem import CatalogSIMEM, ReadSIMEM
import datetime as dt
import pandas as pd

In [3]:
# Buscar dataset
cat = CatalogSIMEM('Datasets')
df_cat = cat.get_data()
set(df_cat['nombreConjuntoDatos'])

{'Actuación del Esquema de Deslastre Automático de Carga (EDAC)',
 'Acumulado anual de los calce u operaciones de las órdenes de demanda en Convocatorias',
 'Acumulado anual de los calce u operaciones de las órdenes de oferta en Convocatorias',
 'Agentes MEM inscritos en el mecanismo Derivex',
 'Ajuste Transacciones TIE',
 'Aportes Energético Largo Plazo',
 'Aportes Energético Mediano Plazo',
 'Aportes Hídricos en Energía',
 'Aportes Hídricos en Energía del Informe Diario de Operación',
 'Aportes Hídricos en Masa',
 'Aportes Hídricos en Masa del Informe Diario',
 'Aportes Hídricos en Porcentaje',
 'Aportes Hídricos en Porcentaje del Informe Diario',
 'Asignaciones de OEF por planta',
 'Auditoria Ejecución Conjuntos de SIMEM',
 'Bandera de Disponibilidad Real',
 'Bandera de arranque Planta térmica para el Despacho Ideal',
 'Bandera de arranque de plantas',
 'Bandera de autorización a desvío del programa de generación',
 'Bandera de inflexibilidades asociadas generaciones de seguridad',
 'Bandera de parada de plantas',
 'Bandera de pruebas de disponibilidad programadas en la operación por el Centro Nacional de Despacho',
 'Bandera para pruebas de disponibilidad',
 'Banderas de pruebas por unidad',
 'CEREUSD',
 'Calce u operaciones de las órdenes de demanda en Convocatorias de Participación en Subasta de Cierre',
 'Calce u operaciones de las órdenes de oferta en Convocatorias de Participación en Subasta de Cierre',
 'Calculo Frecuencia Interrupción Servidores',
 'Cantidad de compra despachada en contratos de largo plazo en kWh',
 'Cantidad de fronteras de UNR por nivel de consumo',
 'Cantidad de fronteras de UNR por nivel de tensión',
 'CantidadHorariaContratosAdjudicadosSICEP',
 'Cantidades de energía por comercializador de contratos adjudicados en subastas del Ministerio (MME)',
 'Cantidades horarias de energía por comercializador de contratos adjudicados en subastas del Ministerio (MME)',
 'Cantidades y precios en contratos de energía del Mercado Mayorista por comercializador',
 'Capacidad de respaldo para operaciones en el Mercado Mayorista de Energía',
 'Capacidad efectiva neta por planta en potencia',
 'Cargo de nivel de tensión 4',
 'Cargo por concepto de remuneración de los planes de pérdidas (CPROG)',
 'Cargos por uso bruto ',
 'Cargos por uso del STN',
 'Cargos por uso en el SDL',
 'Cargos por uso únicos por nivel de tensión (DtUN)',
 'Caudal Descargado por Tipo de Descarga',
 'Causas Generación Seguridad',
 'Cobertura de la demanda de UNR',
 'Cobertura de la demanda de contratos realizados fuera del SICEP',
 'CombustibleUtilizadoParaCalculoCostos',
 'Combustibles y Heat Rate de plantas térmicas del SIN',
 'Compras en bolsa TIE en moneda',
 'Compras en bolsa internacional en moneda',
 'Compras en bolsa nacional en moneda',
 'ConceptosLiquidacionUnidades',
 'Condición del sistema según lo establecido en el Estatuto de Riesgo de Desabastecimiento',
 'Consumo de Combustible Energético Largo Plazo',
 'Consumo de Combustible Energético Mediano Plazo',
 'ConsumosPropios',
 'Coordinación de mantenimientos generadores',
 'Costo Equivalente Real de Energía (CERE)',
 'Costo Equivalente Real de Energía y Costo Equivalente de Energía (CERE y CEE)',
 'Costo Equivalente de Energía (CEE)',
 'Costo Marginal Promedio del Redespacho del Informe Diario de Operación',
 'Costo Marginal Redespacho',
 'Costo Restricciones Asignadas al Agente',
 'Costo Servicios ASIC y CND',
 'Costo de operación y mantenimiento para el precio de escasez',
 'Costo del uso de los activos de transmisión',
 'Costo marginal del Despacho Económico',
 'Costo promedio ponderado en contratos de largo plazo MC',
 'Costo unitario SIMEM y SICEP',
 'Costo unitario promedio diario de reconciliación positiva',
 'Costo unitario responsabilidad comercial de AGC',
 'Costos Marginales Energético Largo Plazo',
 'Costos Marginales Energético Mediano Plazo',
 'Costos de operación, mantenimiento y otros costos variables de generadores térmicos',
 'CostosCombustibleRes1402017',
 'DDVSistema',
 'Datos soporte del proceso de Contratos por Código sic agente, Recurso, versión y horaria',
 'Datos soporte del proceso de Contratos por Recurso, versión y diaria',
 'Datos soporte del proceso de Contratos por versión y horaria',
 'Datos soporte del proceso de Demandas por Código Sic Frontera, Submercado, Tipo enlace, versión y horaria',
 'Datos soporte del proceso de Demandas por Código sic agente, Código sic frontera, Tipo frontera, versión y horaria',
 'Datos soporte del proceso de Demandas por Código sic agente, Mercado comercialización, Sistema transmisión, versión y horaria',
 'Datos soporte del proceso de Demandas por Código sic agente, Recurso, Tipo despacho Recurso, Estado, versión y diaria',
 'Datos soporte del proceso de Demandas por Código sic agente, Recurso, Unidad, versión y horaria',
 'Datos soporte del proceso de Demandas por Código sic agente, versión y horaria',
 'Datos soporte del proceso de Demandas por Recurso, versión y diaria',
 'Datos soporte del proceso de Demandas por Recurso, versión y horaria',
 'Datos soporte del proceso de Demandas por versión y diaria',
 'Datos soporte del proceso de Despacho Ideal por Recurso, versión y horaria',
 'Datos soporte del proceso de Despacho Ideal por versión y diaria',
 'Datos soporte del proceso de liquidación por Código sic agente, Recurso, Tipo combustible, versión y mensual',
 'Datos soporte del proceso de liquidación por Código sic agente, Recurso, Unidad, versión y horaria',
 'Datos soporte del proceso de liquidación por Código sic agente, Recurso, versión y diaria',
 'Datos soporte del proceso de liquidación por Código sic agente, Recurso, versión y horaria',
 'Datos soporte del proceso de liquidación por Código sic agente, versión y diaria',
 'Datos soporte del proceso de liquidación por Código sic agente, versión y horaria',
 'Datos soporte del proceso de liquidación por Código sic agente, versión y mensual',
 'Datos soporte del proceso de liquidación por Código sic agente, versión, horaria y mensual',
 'Datos soporte del proceso de liquidación por Recurso, Tipo combustible, versión y mensual',
 'Datos soporte del proceso de liquidación por Recurso, versión y diaria',
 'Datos soporte del proceso de liquidación por Recurso, versión y horaria',
 'Datos soporte del proceso de liquidación por Tipo combustible, versión y mensual',
 'Datos soporte del proceso de liquidación por descripción convocatoria, Código convocatoria subasta, Fecha asignación subasta, versión y mensual',
 'Datos soporte del proceso de liquidación por versión y diaria',
 'Datos soporte del proceso de liquidación por versión y horaria',
 'Datos soporte del proceso de liquidación por versión y mensual',
 'DdaReal_TipoMercado',
 'Declaración de respaldo horaria para cada planta y/o unidad',
 'Delta de generación programada',
 'Deltas holgura arriba y abajo horarias',
 'Deltas incremento nacional e internacional',
 'Demanda Energético Largo Plazo',
 'Demanda Energético Mediano Plazo',
 'Demanda comercial',
 'Demanda comercial internacional',
 'Demanda real',
 'DemandaComercialColombiaEcuadorVenezuela',
 'DemandaComercialLiquidacionCargo',
 'DemandaComercialTieAgente',
 'DemandaDeCogeneradoresUsoDeRespaldoAgente',
 'DemandaGeneracionAgenteParaAsignarPerdidas',
 'DemandaNoReguladaAgente',
 'DemandaRealInternacionalAgente',
 'DemandaRealORAgente',
 'DemandaReguladaAgente',
 'DemandaSTR',
 'Despacho programado recursos de generación',
 'Desviación diaria de obligación de energía firme negativa',
 'Desviación diaria de obligación de energía firme positiva',
 'Disponibilidad Real de las Unidades de Generación del Sistema',
 'Disponibilidad asociada con arranque utilizando tecnología térmica a gas ciclo carbón',
 'Disponibilidad asociada con arranque utilizando tecnología térmica a gas ciclo sting',
 'Disponibilidad asociada con arranque utilizando tecnología térmica a gas de ciclo abierto',
 'Disponibilidad asociada con arranque utilizando tecnología térmica gas vapor',
 'Disponibilidad comercial por planta',
 'Disponibilidad declarada en el despacho',
 'Disponibilidad horaria de respaldo de OEF ajustada',
 'Disponibilidad horaria declarada total que respalda las OEF',
 'Disponibilidad real',
 'DisponibilidadProgramadaRecursoGeneracion',
 'Duración promedio de los contratos entre agentes',
 'Duración promedio de los contratos producto de convocatorias del SICEP para el mercado regulado',
 'Déficit Energético Largo Plazo',
 'Déficit Energético Mediano Plazo',
 'Energía Firme del Cargo por Confiabilidad verificada por el Centro Nacional de Despacho',
 'Energía calculada para plantas hidráulicas por reconciliación positiva asociada a la exportación hacia Ecuador',
 'Energía de Referencia para el Mercado Secundario',
 'Energía de referencia para el Sistema de Transmisión Nacional',
 'Energía horaria de los contadores',
 'Energía promedio de los contratos de convocatorias del SICEP con destino al mercado regulado del Sistema Interconectado Nacional',
 'Energía promedio de los contratos del SICEP para el mercado regulado por comercializador',
 'Energía promedio de los contratos entre agentes del Sistema Interconectado Nacional',
 'Energía promedio mensual de contratos con UNR para el total del SIN',
 'Energía promedio mensual de contratos con UNR por mercado de comercialización',
 'Estad?sticas SIMEM',
 'Estado del reporte de facturación de Contratos UNR',
 'Estadísticas anuales de las convocatorias del SICEP para el mercado regulado',
 'Estadísticas de Horas de indisponibilidad de las líneas de transmisión nacional y regional del SIN',
 'Estadísticas de contratos de Demanda Desconectable Voluntaria (DDV)',
 'Estadísticas de contratos del mercado secundario',
 'Estadísticas de los pronósticos de energía horaria y demanda de energía atendida horaria por periodo y por mercado de comercialización',
 'Estadísticas de monto de indisponibilidad de las líneas de transmisión nacional y regional del SIN',
 'Estadísticas de precios de los contratos adjudicados en subastas del Ministerio (MME)',
 'Estadísticas de precios por comercializador de los contratos adjudicados en subastas del Ministerio (MME)',
 'Estadísticas del Costo Unitario de Reconciliación Positiva',
 'Estadísticas horarias de precios de los contratos adjudicados en subastas del Ministerio (MME)',
 'Estadísticas horarias de precios por comercializador de los contratos adjudicados en subastas del Ministerio (MME)',
 'Estudio Esquema de Desconexión Automático de Carga EDAC',
 'Estudio Interconexión Colombia Ecuador',
 'Eventos de Demanda No Atendida',
 'Eventos de Frecuencia',
 'Eventos de Tensión fuera de Rango',
 'Eventos en unidades de Generación',
 'Evolución histórica anual de las estadísticas generales de las convocatorias SICEP con destino al mercado regulado',
 'Fecha de retiro de unidades de generación',
 'Fondo de Apoyo Financiero para la Energización de las Zonas Rurales Interconectadas (FAER)',
 'Fondo de apoyo a zonas no interconectadas (FAZNI)',
 'Fondo de energía social (FOES)',
 'Garantía de reserva de capacidad de transporte',
 'GeneracionIdealInternacionalVenezuelaRecursoGeneracion',
 'GeneracionIdealSinConsiderarContratos',
 'GeneracionIdealTotalConsiderandoContratos',
 'GeneracionProgramaGrupoGeneracion',
 'GeneracionesCandidatasParaSerinflexiblesCND',
 'Generación Energético Largo Plazo',
 'Generación Energético Mediano Plazo',
 'Generación Ideal Internacional Ecuador por planta',
 'Generación Ideal por planta',
 'Generación Programada Redespacho por Planta',
 'Generación Real y Programada en las Plantas de Generación',
 'Generación ideal flexible para demanda no domestica Venezuela ',
 'Generación ideal nacional por planta',
 'Generación programada en el despacho',
 'Generación programada en el redespacho',
 'Generación programada incluyendo autorización a desvío',
 'Generación real',
 'Histórico Posición abierta por contrato II Open interest II',
 'Histórico anual de los precios de referencia para el traslado al Mercado Regulado',
 'Histórico de eventos en Activos de Transmisión del Sistema de Transmisión Nacional',
 'Histórico de eventos en Líneas de Transmisión del Sistema de Transmisión Nacional',
 'Histórico de eventos en Unidades de Generación',
 'Horas de indisponibilidad de las líneas de transmisión nacional y regional del SIN',
 'Importaciones Netas Energético Largo Plazo',
 'Importaciones Netas Energético Mediano Plazo',
 'Indicadores de calidad del servicio SAIDI y SAIFI pais',
 'Indices VERE y VEREC Energético Largo Plazo',
 'Indices VERE y VEREC Energético Mediano Plazo',
 'InflexibilidadAsignadaProcesoComercial',
 'Inflexibilidades no asociadas con generación de seguridad',
 'Información de Transferencias Internacionales',
 'Informe Anual de Operadores de Red',
 'Informe Energético de Corto Plazo Despacho Horario',
 'Informe Energético de Corto Plazo Embalses',
 'Informe anual de auditoría de costos de combustible para el cálculo del precio marginal de escasez',
 'Informe de reevaluación de parámetros de regulación secundaria de frecuencia AGC',
 'Informe de resultados del despacho económico',
 'Informe semestral de planeamiento operativo eléctrico de largo plazo',
 'Informe trimestral de auditoría de costos de combustible reportados para la operación',
 'Informe trimestral de planeamiento operativo eléctrico de mediano plazo',
 'Insumos para el Precio Marginal de Escasez',
 'InsumosPrecioEscasezMarginalHeatRate',
 'Interrupciones en servidores Sicep',
 'Limitación de suministro en bolsa según la Res. CREG 001 de 2003',
 'Limitación de suministros a usuarios finales según la Res. CREG 116 de 1998',
 'Listado de Embalses que sirven al Sistema Interconectado Nacional',
 'Listado de Operadores de activos del Sistema Interconectado Nacional',
 'Listado de Subestaciones del STN y el STR',
 'Listado de Subáreas Operativas del Sistema de Interconectado Nacional',
 'Listado de agentes registrados',
 'Listado de fronteras de UNR vigentes',
 'Listado de plantas de generación en pruebas',
 'Listado de series hidrológicas',
 'Listado de unidades de generación',
 'Listado de Áreas Operativas del Sistema de Interconectado Nacional',
 'Maestra para la ejecución de información soporte Diaria',
 'Maestra para la ejecución de información soporte Mensual',
 'Magnitud compras transacciones en bolsa en energía',
 'Magnitud de desviación',
 'Magnitud de generación de seguridad del país importador',
 'Magnitud de reconciliación positiva arranque',
 'Magnitud de reconciliación positiva para plantas que no realizan AGC',
 'Magnitud de reconciliación positiva para plantas que prestan servicio de AGC',
 'Magnitud energía en bolsa internacional a cargo',
 'Magnitud energía en bolsa nacional a cargo',
 'Magnitud responsabilidad comercial AGC',
 'Magnitud ventas en bolsa internacional en energía',
 'Magnitud ventas en bolsa nacional en energía',
 'Magnitud ventas transacciones en bolsa en energía',
 'MagnitudEnergiaExcentariaEntregadaPorCogeneradorAutogeneradorPlantaMenor',
 'Meteorología local en Plantas Eólicas',
 'Meteorología local en Plantas Solares',
 'MgDesvFueraBanda_NoAGC_TRGC',
 'Montos de garantías para cubrir las transacciones en el mercado de energía mayorista',
 'Montos de garantías para cubrir las transacciones en el mercado de energía mayorista agregados',
 'Montos de garantías y mecanismos alternativos para cubrir las transacciones en el mercado de energía mayorista',
 'Montos de garantías y mecanismos alternativos para cubrir las transacciones en el mercado de energía mayorista agregados',
 'Montos por indisponibilidad de las líneas de transmisión nacional y regional del SIN en COP',
 'Nivel de Probabilidad de Vertimiento',
 'Nivel de embalse declarado por el agente diariamente',
 'Nivel embalse reportado menos compromisos EVE embalsados por planta',
 'Niveles Mínimos Operativos de Embalses de invierno',
 'Niveles Mínimos Operativos de Embalses de verano',
 'Número de intentos para cumplir pruebas de disponiblidad',
 'OEFDiaria_TSubasta',
 'Obligación de energía firme por submercado',
 'Oportunidad en el reporte de información por parte de XM, el Administrador del SIMEM y otros',
 'Oportunidad en la entrega de información por parte de los agentes de contratos UNR',
 'Oportunidad en la entrega de información por parte de los agentes de contratos largo plazo',
 'Otros costos variables asociados al SIN',
 'Otros costos variables hidráulicos y térmicos',
 'PPBO',
 'Panorama energético Corto Plazo Embalse',
 'Panorama energético Corto Plazo Supuestos y Resultados',
 'Participación en Convocatorias de Participación en Subasta de Cierre de agentes registrados',
 'Parámetros técnicos de las líneas de transmisión',
 'Parámetros técnicos de las plantas de generación',
 'Parámetros técnicos de las plantas de generación Eólicas',
 'Parámetros técnicos de las plantas de generación Hidráulicas',
 'Parámetros técnicos de las plantas de generación Solares',
 'Parámetros técnicos de las plantas de generación Térmicas',
 'PerdidasAgenteGeneradoresAgente',
 'PerdidasDemandaInternacionalAgente',
 'PerdidasDemandaReguladaAgente',
 'PerdidasDemandaTIEAgente',
 'Porcentaje Estimado de cobertura con contratos de convocatorias del SICEP para el mercado regulado',
 'Porcentaje Estimado de cobertura con contratos entre agentes',
 'Potencia asociada con la holgura',
 'Precio de Oferta Declarado',
 'Precio de Oferta de Arranque y Parada por recurso USD',
 'Precio de Transacciones en Bolsa',
 'Precio de bolsa horario',
 'Precio de bolsa ponderado',
 'Precio de cierre de los mecanismos de asignación de OEF',
 'Precio de escasez',
 'Precio de escasez ponderado',
 'Precio de oferta de la planta en el proceso del despacho ideal, en COP/kWh',
 'Precio de oferta de la planta para cada configuración ofertada en el proceso del despacho ideal, en COP/kWh',
 'Precio de oferta en el nodo frontera para exportación',
 'Precio oferta arranque y parada por unidad para el combustible USD',
 'PrecioBolsaPromedioPonderado',
 'PrecioOfertaArranqueParadaUnidadCOP',
 'PrecioOfertaArranqueParadaUnidadUSD',
 'PrecioOfertaGeneradoresIdeal',
 'PrecioPromPonContratosLPMercadoReg',
 'Precios de escasez del Cargo por Confiabilidad',
 'Precios de escasez promedio ponderado por agente',
 'Precios futuros horarios mensuales de contratos con UNR para el total del SIN',
 'Precios futuros horarios mensuales de contratos con UNR por mercado de comercialización',
 'Precios futuros mensuales de contratos con UNR para el total del SIN',
 'Precios futuros mensuales de contratos con UNR por mercado de comercialización',
 'Precios futuros y estadísticas de los contratos de convocatorias del SICEP para el mercado regulado',
 'Precios futuros y estadísticas de los contratos de convocatorias del SICEP para el mercado regulado por comercializador',
 'Precios futuros y estadísticas de los contratos entre agentes',
 'Precios futuros y estadísticas de los contratos entre agentes por comercializador y generador',
 'Precios horarios futuros y estadísticas de los contratos de convocatorias del SICEP para el mercado regulado',
 'Precios horarios futuros y estadísticas de los contratos de convocatorias del SICEP para el mercado regulado por comercializador',
 'Precios horarios futuros y estadísticas de los contratos entre agentes',
 'Precios horarios futuros y estadísticas de los contratos entre agentes por comercializador y generador',
 'Precios horarios y estadísticas de los contratos de convocatorias del SICEP para el mercado regulado',
 'Precios horarios y estadísticas de los contratos de convocatorias del SICEP para el mercado regulado por comercializador',
 'Precios horarios y estadísticas de los contratos entre agentes',
 'Precios horarios y estadísticas de los contratos entre agentes por comercializador',
 'Precios horarios y estadísticas de los contratos entre agentes por generador',
 'Precios promedios horarios mensuales de contratos con UNR para el total del SIN',

In [7]:
#Precio de bolsa ponderado
nombre = "Aportes Hídricos en Energía"
df_cat[df_cat["nombreConjuntoDatos"] == nombre]

,idDataset,nombreConjuntoDatos,fechaPublicacion,fechaActualizacion,inicioDato,finDato,fechaDescarga,urlConexionAPI,urlConjuntoDatos,tipoPublicacion
350,BA1C55,Aportes Hídricos en Energía,2023-09-29T12:08:14.157,2025-11-21T08:23:22.753,2013-01-01T00:00:00,2025-11-20T00:00:00,2025-05-02T20:45:18.77,https://www.simem.coPublicData?startDate=2025-...,https://www.simem.co/datadetail/ba1c5513-7dc3-...,Público

In [17]:
# Descargar
nombre = "Demanda real"
id_dataset = df_cat[df_cat["nombreConjuntoDatos"] == nombre]["idDataset"].values[0]
fecha_inicio_str = "2024-01-01"
fecha_inicio = dt.datetime.strptime(fecha_inicio_str, "%Y-%m-%d")
fecha_fin_str = "2024-01-31"
fecha_fin = dt.datetime.strptime(fecha_fin_str, "%Y-%m-%d")
list_df = []
keep = True

while keep:
    fecha_part = dt.datetime(fecha_inicio.year, 12, 31)
    fecha_part_str = dt.datetime.strftime(fecha_part, "%Y-%m-%d")
    print(f"{fecha_inicio_str} a {fecha_part_str}")
    if fecha_part >= fecha_fin:
        reader = ReadSIMEM(id_dataset, fecha_inicio_str, fecha_fin_str)
        keep = False
    else:
        reader = ReadSIMEM(id_dataset, fecha_inicio_str, fecha_part_str)
    
    df = reader.main(filter=False)
    #df = df[df['CodigoVariable'] == 'PB_Nal']
    list_df.append(df)
    del df

    fecha_inicio = dt.datetime(fecha_inicio.year + 1, 1, 1)
    fecha_inicio_str = dt.datetime.strftime(fecha_inicio, "%Y-%m-%d")

df = pd.concat(list_df)
#df.to_csv("Precio_Energia.csv", index=False, sep=",")

2024-01-01 a 2024-12-31
****************************************************************************************************
Initializing object
The object has been initialized with the dataset: "Demanda real"
****************************************************************************************************
Inicio consulta sincronica
Creacion url: 0.0002079010009765625
Extraccion de registros: 3.8828420639038086
End of data extracting process
****************************************************************************************************

In [18]:
df

,CodigoVariable,FechaHora,CodigoSICAgente,TipoMercado,Version,Valor,UnidadMedida,CodigoDuracion
0,DdaReal,2024-01-31 05:00:00,CMMC,Regulado,TX5,857272.46,kWh,PT1H
1,DdaReal,2024-01-31 04:00:00,CMMC,Regulado,TX5,887735.62,kWh,PT1H
2,DdaReal,2024-01-31 03:00:00,CMMC,Regulado,TX5,915485.94,kWh,PT1H
3,DdaReal,2024-01-31 02:00:00,CMMC,Regulado,TX5,946861.34,kWh,PT1H
4,DdaReal,2024-01-31 01:00:00,CMMC,Regulado,TX5,989096.64,kWh,PT1H
...,...,...,...,...,...,...,...,...
65467,DdaReal,2024-01-01 01:00:00,ENBC,Regulado,TX5,4441.11,kWh,PT1H
65468,DdaReal,2024-01-01 02:00:00,ENBC,Regulado,TX5,4373.12,kWh,PT1H
65469,DdaReal,2024-01-01 03:00:00,ENBC,Regulado,TX5,4204.81,kWh,PT1H
65470,DdaReal,2024-01-01 04:00:00,ENBC,Regulado,TX5,4033.81,kWh,PT1H
65471,DdaReal,2024-01-01 05:00:00,ENBC,Regulado,TX5,4029.09,kWh,PT1H

In [ ]:
# Descargar
nombre = "Precio de bolsa ponderado"
id_dataset = df_cat[df_cat["nombreConjuntoDatos"] == nombre]["idDataset"].values[0]
fecha_inicio_str = "2024-01-01"
fecha_inicio = dt.datetime.strptime(fecha_inicio_str, "%Y-%m-%d")
fecha_fin_str = "2024-01-31"
fecha_fin = dt.datetime.strptime(fecha_fin_str, "%Y-%m-%d")
list_df = []
keep = True

while keep:
    fecha_part = dt.datetime(fecha_inicio.year, 12, 31)
    fecha_part_str = dt.datetime.strftime(fecha_part, "%Y-%m-%d")
    print(f"{fecha_inicio_str} a {fecha_part_str}")
    if fecha_part >= fecha_fin:
        reader = ReadSIMEM(id_dataset, fecha_inicio_str, fecha_fin_str)
        keep = False
    else:
        reader = ReadSIMEM(id_dataset, fecha_inicio_str, fecha_part_str)
    
    df = reader.main(filter=False)
    #df = df[df['CodigoVariable'] == 'PB_Nal']
    list_df.append(df)
    del df

    fecha_inicio = dt.datetime(fecha_inicio.year + 1, 1, 1)
    fecha_inicio_str = dt.datetime.strftime(fecha_inicio, "%Y-%m-%d")

df = pd.concat(list_df)
#df.to_csv("Precio_Energia.csv", index=False, sep=",")

2024-01-01 a 2024-12-31
****************************************************************************************************
Initializing object
The object has been initialized with the dataset: "Precio de bolsa ponderado"
****************************************************************************************************
Inicio consulta sincronica
Creacion url: 0.00031685829162597656
Extraccion de registros: 3.0175411701202393
End of data extracting process
****************************************************************************************************

In [ ]:
# Descargar
id_dataset = "EC6945"
fecha_inicio_str = "2015-01-01"
fecha_inicio = dt.datetime.strptime(fecha_inicio_str, "%Y-%m-%d")
fecha_fin_str = "2025-09-30"
fecha_fin = dt.datetime.strptime(fecha_fin_str, "%Y-%m-%d")
list_df = []
keep = True

while keep:
    fecha_part = dt.datetime(fecha_inicio.year, 12, 31)
    fecha_part_str = dt.datetime.strftime(fecha_part, "%Y-%m-%d")
    print(f"{fecha_inicio_str} a {fecha_part_str}")
    if fecha_part >= fecha_fin:
        reader = ReadSIMEM(id_dataset, fecha_inicio_str, fecha_fin_str)
        keep = False
    else:
        reader = ReadSIMEM(id_dataset, fecha_inicio_str, fecha_part_str)
    
    df = reader.main(filter=False)
    df = df[df['CodigoVariable'] == 'PB_Nal']
    list_df.append(df)
    del df

    fecha_inicio = dt.datetime(fecha_inicio.year + 1, 1, 1)
    fecha_inicio_str = dt.datetime.strftime(fecha_inicio, "%Y-%m-%d")

df = pd.concat(list_df)
df.to_csv("Precio_Energia.csv", index=False, sep=",")

2015-01-01 a 2015-12-31
****************************************************************************************************
Initializing object
The object has been initialized with the dataset: "Precio de bolsa horario"
****************************************************************************************************
Inicio consulta sincronica
Creacion url: 0.0010020732879638672
Extraccion de registros: 74.48386979103088
End of data extracting process
****************************************************************************************************
2016-01-01 a 2016-12-31
****************************************************************************************************
Initializing object
The object has been initialized with the dataset: "Precio de bolsa horario"
****************************************************************************************************
Inicio consulta sincronica
Creacion url: 0.0008471012115478516
Extraccion de registros: 55.51651096343994
End of data extracting process
****************************************************************************************************
2017-01-01 a 2017-12-31
****************************************************************************************************
Initializing object
The object has been initialized with the dataset: "Precio de bolsa horario"
****************************************************************************************************
Inicio consulta sincronica
Creacion url: 0.00074005126953125
Extraccion de registros: 54.85504198074341
End of data extracting process
****************************************************************************************************
2018-01-01 a 2018-12-31
****************************************************************************************************
Initializing object
The object has been initialized with the dataset: "Precio de bolsa horario"
****************************************************************************************************
Inicio consulta sincronica
Creacion url: 0.0007100105285644531
Extraccion de registros: 52.80686402320862
End of data extracting process
****************************************************************************************************
2019-01-01 a 2019-12-31
****************************************************************************************************
Initializing object
The object has been initialized with the dataset: "Precio de bolsa horario"
****************************************************************************************************
Inicio consulta sincronica
Creacion url: 0.0005450248718261719
Extraccion de registros: 50.84695601463318
End of data extracting process
****************************************************************************************************
2020-01-01 a 2020-12-31
****************************************************************************************************
Initializing object
The object has been initialized with the dataset: "Precio de bolsa horario"
****************************************************************************************************
Inicio consulta sincronica
Creacion url: 0.0006580352783203125
Extraccion de registros: 50.953097105026245
End of data extracting process
****************************************************************************************************
2021-01-01 a 2021-12-31
****************************************************************************************************
Initializing object
The object has been initialized with the dataset: "Precio de bolsa horario"
****************************************************************************************************
Inicio consulta sincronica
Creacion url: 0.00078582763671875
Extraccion de registros: 52.885448932647705
End of data extracting process
****************************************************************************************************
2022-01-01 a 2022-12-31
****************************************************************************************************
Initializing object
The object has been initialized with the dataset: "Precio de bolsa horario"
****************************************************************************************************
Inicio consulta sincronica
Creacion url: 0.0007050037384033203
Extraccion de registros: 54.76621985435486
End of data extracting process
****************************************************************************************************
2023-01-01 a 2023-12-31
****************************************************************************************************
Initializing object
The object has been initialized with the dataset: "Precio de bolsa horario"
****************************************************************************************************
Inicio consulta sincronica
Creacion url: 0.0007157325744628906
Extraccion de registros: 51.14032006263733
End of data extracting process
****************************************************************************************************
2024-01-01 a 2024-12-31
****************************************************************************************************
Initializing object
The object has been initialized with the dataset: "Precio de bolsa horario"
****************************************************************************************************
Inicio consulta sincronica
Creacion url: 0.0004448890686035156
Extraccion de registros: 53.87249422073364
End of data extracting process
****************************************************************************************************
2025-01-01 a 2025-12-31
****************************************************************************************************
Initializing object
The object has been initialized with the dataset: "Precio de bolsa horario"
****************************************************************************************************
Inicio consulta sincronica
Creacion url: 0.000637054443359375
Extraccion de registros: 39.186732053756714
End of data extracting process
****************************************************************************************************