<a id="section1"></a>
# Instalación de la librería
Ejecutar el siguiente comando en el CMD para instalar la librería de python.

In [9]:
#pip install pydataxm

<a id="section2"></a>
# Importación de librerías

In [10]:
from pydataxm.pydatasimem import CatalogSIMEM, ReadSIMEM
import datetime as dt
import pandas as pd
import calendar

In [11]:
# Buscar dataset
cat = CatalogSIMEM("Datasets")
df_cat = cat.get_data()

listado = set(df_cat["nombreConjuntoDatos"])

for i in listado:
    if "bilateral" in i.lower():
        print(i)

Venta en contratos bilaterales de largo plazo por vendedor en energía

In [12]:
listado

{'Actuación del Esquema de Deslastre Automático de Carga (EDAC)',
 'Acumulado anual de los calce u operaciones de las órdenes de demanda en Convocatorias',
 'Acumulado anual de los calce u operaciones de las órdenes de oferta en Convocatorias',
 'Agentes MEM inscritos en el mecanismo Derivex',
 'Ajuste Transacciones TIE',
 'Aportes Energético Largo Plazo',
 'Aportes Energético Mediano Plazo',
 'Aportes Hídricos en Energía',
 'Aportes Hídricos en Energía del Informe Diario de Operación',
 'Aportes Hídricos en Masa',
 'Aportes Hídricos en Masa del Informe Diario',
 'Aportes Hídricos en Porcentaje',
 'Aportes Hídricos en Porcentaje del Informe Diario',
 'Asignaciones de OEF por planta',
 'Auditoria Ejecución Conjuntos de SIMEM',
 'Bandera de Disponibilidad Real',
 'Bandera de arranque Planta térmica para el Despacho Ideal',
 'Bandera de arranque de plantas',
 'Bandera de autorización a desvío del programa de generación',
 'Bandera de inflexibilidades asociadas generaciones de seguridad',
 'Bandera de parada de plantas',
 'Bandera de pruebas de disponibilidad programadas en la operación por el Centro Nacional de Despacho',
 'Bandera para pruebas de disponibilidad',
 'Banderas de pruebas por unidad',
 'Calce u operaciones de las órdenes de demanda en Convocatorias de Participación en Subasta de Cierre',
 'Calce u operaciones de las órdenes de oferta en Convocatorias de Participación en Subasta de Cierre',
 'Calculo Frecuencia Interrupción Servidores',
 'Cantidad de compra despachada en contratos de largo plazo en kWh',
 'Cantidad de fronteras de UNR por nivel de consumo',
 'Cantidad de fronteras de UNR por nivel de tensión',
 'Cantidad ventas en contratos del SICEP',
 'Cantidades de energía por comercializador de contratos adjudicados en subastas del Ministerio (MME)',
 'Cantidades horarias de energía por comercializador de contratos adjudicados en subastas del Ministerio (MME)',
 'Cantidades y precios en contratos de energía del Mercado Mayorista por comercializador',
 'Capacidad de respaldo para operaciones en el Mercado Mayorista de Energía',
 'Capacidad efectiva neta por planta en potencia',
 'Cargo de nivel de tensión 4',
 'Cargo por concepto de remuneración de los planes de pérdidas (CPROG)',
 'Cargos por uso bruto ',
 'Cargos por uso del STN',
 'Cargos por uso en el SDL',
 'Cargos por uso únicos por nivel de tensión (DtUN)',
 'Caudal Descargado por Tipo de Descarga',
 'Causas Generación Seguridad',
 'Cobertura de la demanda de UNR',
 'Cobertura de la demanda de contratos realizados fuera del SICEP',
 'Combustibles y Heat Rate de plantas térmicas del SIN',
 'Compras en bolsa TIE en moneda',
 'Compras en bolsa internacional en moneda',
 'Compras en bolsa nacional en moneda',
 'Conceptos adicionados a través de restricciones',
 'Condición del sistema según lo establecido en el Estatuto de Riesgo de Desabastecimiento',
 'Consumo de Combustible Energético Largo Plazo',
 'Consumo de Combustible Energético Mediano Plazo',
 'Coordinación de mantenimientos generadores',
 'Costo Equivalente Real de Energía (CERE)',
 'Costo Equivalente de Energía (CEE)',
 'Costo Marginal Promedio del Redespacho del Informe Diario de Operación',
 'Costo Marginal Redespacho',
 'Costo Restricciones Asignadas al Agente',
 'Costo Servicios ASIC y CND',
 'Costo de operación y mantenimiento para el precio de escasez',
 'Costo del uso de los activos de transmisión',
 'Costo marginal del Despacho Económico',
 'Costo promedio ponderado en contratos de largo plazo MC',
 'Costo unitario SIMEM y SICEP',
 'Costo unitario promedio diario de reconciliación positiva',
 'Costo unitario responsabilidad comercial de AGC',
 'Costos Marginales Energético Largo Plazo',
 'Costos Marginales Energético Mediano Plazo',
 'Costos de operación, mantenimiento y otros costos variables de generadores térmicos',
 'Datos soporte del proceso de Contratos por Código sic agente, Recurso, versión y horaria',
 'Datos soporte del proceso de Contratos por Recurso, versión y diaria',
 'Datos soporte del proceso de Contratos por versión y horaria',
 'Datos soporte del proceso de Demandas por Código Sic Frontera, Submercado, Tipo enlace, versión y horaria',
 'Datos soporte del proceso de Demandas por Código sic agente, Código sic frontera, Tipo frontera, versión y horaria',
 'Datos soporte del proceso de Demandas por Código sic agente, Mercado comercialización, Sistema transmisión, versión y horaria',
 'Datos soporte del proceso de Demandas por Código sic agente, Recurso, Tipo despacho Recurso, Estado, versión y diaria',
 'Datos soporte del proceso de Demandas por Código sic agente, Recurso, Unidad, versión y horaria',
 'Datos soporte del proceso de Demandas por Código sic agente, versión y horaria',
 'Datos soporte del proceso de Demandas por Recurso, versión y diaria',
 'Datos soporte del proceso de Demandas por Recurso, versión y horaria',
 'Datos soporte del proceso de Demandas por versión y diaria',
 'Datos soporte del proceso de Despacho Ideal por Recurso, versión y horaria',
 'Datos soporte del proceso de liquidación por Código sic agente, Recurso, Tipo combustible, versión y mensual',
 'Datos soporte del proceso de liquidación por Código sic agente, Recurso, Unidad, versión y horaria',
 'Datos soporte del proceso de liquidación por Código sic agente, Recurso, versión y diaria',
 'Datos soporte del proceso de liquidación por Código sic agente, Recurso, versión y horaria',
 'Datos soporte del proceso de liquidación por Código sic agente, versión y diaria',
 'Datos soporte del proceso de liquidación por Código sic agente, versión y horaria',
 'Datos soporte del proceso de liquidación por Código sic agente, versión y mensual',
 'Datos soporte del proceso de liquidación por Código sic agente, versión, horaria y mensual',
 'Datos soporte del proceso de liquidación por Recurso, Tipo combustible, versión y mensual',
 'Datos soporte del proceso de liquidación por Recurso, versión y diaria',
 'Datos soporte del proceso de liquidación por Recurso, versión y horaria',
 'Datos soporte del proceso de liquidación por Tipo combustible, versión y mensual',
 'Datos soporte del proceso de liquidación por descripción convocatoria, Código convocatoria subasta, Fecha asignación subasta, versión y mensual',
 'Datos soporte del proceso de liquidación por versión y diaria',
 'Datos soporte del proceso de liquidación por versión y horaria',
 'Datos soporte del proceso de liquidación por versión y mensual',
 'Declaración de respaldo horaria para cada planta y/o unidad',
 'Delta de generación programada',
 'Deltas holgura arriba y abajo horarias',
 'Deltas incremento nacional e internacional',
 'Demanda Energético Largo Plazo',
 'Demanda Energético Mediano Plazo',
 'Demanda comercial',
 'Demanda comercial internacional',
 'Demanda real',
 'Despacho programado recursos de generación',
 'Desviación diaria de obligación de energía firme negativa',
 'Desviación diaria de obligación de energía firme positiva',
 'Disponibilidad Real de las Unidades de Generación del Sistema',
 'Disponibilidad asociada con arranque utilizando tecnología térmica a gas ciclo carbón',
 'Disponibilidad asociada con arranque utilizando tecnología térmica a gas ciclo sting',
 'Disponibilidad asociada con arranque utilizando tecnología térmica a gas de ciclo abierto',
 'Disponibilidad asociada con arranque utilizando tecnología térmica gas vapor',
 'Disponibilidad comercial por planta',
 'Disponibilidad horaria de respaldo de OEF ajustada',
 'Disponibilidad horaria declarada total que respalda las OEF',
 'Disponibilidad programada',
 'Disponibilidad real',
 'Duración promedio de los contratos entre agentes',
 'Duración promedio de los contratos producto de convocatorias del SICEP para el mercado regulado',
 'Déficit Energético Largo Plazo',
 'Déficit Energético Mediano Plazo',
 'Energía Firme del Cargo por Confiabilidad verificada por el Centro Nacional de Despacho',
 'Energía calculada para plantas hidráulicas por reconciliación positiva asociada a la exportación hacia Ecuador',
 'Energía de Referencia para el Mercado Secundario',
 'Energía de referencia para el Sistema de Transmisión Nacional',
 'Energía horaria de los contadores',
 'Energía promedio de los contratos de convocatorias del SICEP con destino al mercado regulado del Sistema Interconectado Nacional',
 'Energía promedio de los contratos del SICEP para el mercado regulado por comercializador',
 'Energía promedio de los contratos entre agentes del Sistema Interconectado Nacional',
 'Energía promedio mensual de contratos con UNR para el total del SIN',
 'Energía promedio mensual de contratos con UNR por mercado de comercialización',
 'Estad?sticas SIMEM',
 'Estadísticas anuales de las convocatorias del SICEP para el mercado regulado',
 'Estadísticas de Horas de indisponibilidad de las líneas de transmisión nacional y regional del SIN',
 'Estadísticas de contratos de Demanda Desconectable Voluntaria (DDV)',
 'Estadísticas de contratos del mercado secundario',
 'Estadísticas de los pronósticos de energía horaria y demanda de energía atendida horaria por periodo y por mercado de comercialización',
 'Estadísticas de monto de indisponibilidad de las líneas de transmisión nacional y regional del SIN',
 'Estadísticas de precios de los contratos adjudicados en subastas del Ministerio (MME)',
 'Estadísticas de precios por comercializador de los contratos adjudicados en subastas del Ministerio (MME)',
 'Estadísticas del Costo Unitario de Reconciliación Positiva',
 'Estadísticas horarias de precios de los contratos adjudicados en subastas del Ministerio (MME)',
 'Estadísticas horarias de precios por comercializador de los contratos adjudicados en subastas del Ministerio (MME)',
 'Estudio Esquema de Desconexión Automático de Carga EDAC',
 'Estudio Interconexión Colombia Ecuador',
 'Eventos de Demanda No Atendida',
 'Eventos de Frecuencia',
 'Eventos de Tensión fuera de Rango',
 'Eventos en unidades de Generación',
 'Evolución histórica anual de las estadísticas generales de las convocatorias SICEP con destino al mercado regulado',
 'Fecha de retiro de unidades de generación',
 'Fondo de Apoyo Financiero para la Energización de las Zonas Rurales Interconectadas (FAER)',
 'Fondo de apoyo a zonas no interconectadas (FAZNI)',
 'Fondo de energía social (FOES)',
 'Garantía de reserva de capacidad de transporte',
 'Generaciones candidatas a ser inflexibles',
 'Generación Energético Largo Plazo',
 'Generación Energético Mediano Plazo',
 'Generación Ideal por planta',
 'Generación Programada Redespacho por Planta',
 'Generación Real y Programada en las Plantas de Generación',
 'Generación ideal flexible para demanda no domestica Venezuela ',
 'Generación ideal internacional Ecuador por planta',
 'Generación ideal internacional Venezuela por recurso planta',
 'Generación ideal nacional por planta',
 'Generación programada en el despacho',
 'Generación programada en el redespacho',
 'Generación programada incluyendo autorización a desvío',
 'Generación real',
 'Histórico Posición abierta por contrato II Open interest II',
 'Histórico anual de los precios de referencia para el traslado al Mercado Regulado',
 'Histórico de eventos en Activos de Transmisión del Sistema de Transmisión Nacional',
 'Histórico de eventos en Líneas de Transmisión del Sistema de Transmisión Nacional',
 'Histórico de eventos en Unidades de Generación',
 'Holgura horaria superior e inferior',
 'Horas de indisponibilidad de las líneas de transmisión nacional y regional del SIN',
 'Importaciones Netas Energético Largo Plazo',
 'Importaciones Netas Energético Mediano Plazo',
 'Indices VERE y VEREC Energético Largo Plazo',
 'Indices VERE y VEREC Energético Mediano Plazo',
 'Inflexibilidad asignada en el proceso comercial',
 'Inflexibilidades no asociadas con generación de seguridad',
 'Información de Transferencias Internacionales',
 'Informe Anual de Operadores de Red',
 'Informe anual de auditoría de costos de combustible para el cálculo del precio marginal de escasez',
 'Informe de reevaluación de parámetros de regulación secundaria de frecuencia AGC',
 'Informe de resultados del despacho económico',
 'Informe semestral de planeamiento operativo eléctrico de largo plazo',
 'Informe trimestral de auditoría de costos de combustible reportados para la operación',
 'Informe trimestral de planeamiento operativo eléctrico de mediano plazo',
 'Insumos para el Precio Marginal de Escasez',
 'Limitación de suministro en bolsa según la Res. CREG 001 de 2003',
 'Limitación de suministros a usuarios finales según la Res. CREG 116 de 1998',
 'Listado de Embalses que sirven al Sistema Interconectado Nacional',
 'Listado de Operadores de activos del Sistema Interconectado Nacional',
 'Listado de Subestaciones del STN y el STR',
 'Listado de Subáreas Operativas del Sistema de Interconectado Nacional',
 'Listado de agentes registrados',
 'Listado de mantenimientos',
 'Listado de plantas de generación en pruebas',
 'Listado de series hidrológicas',
 'Listado de unidades de generación',
 'Listado de Áreas Operativas del Sistema de Interconectado Nacional',
 'Magnitud compras transacciones en bolsa en energía',
 'Magnitud de desviación',
 'Magnitud de generación de seguridad del país importador',
 'Magnitud de reconciliación positiva arranque',
 'Magnitud de reconciliación positiva para plantas que no realizan AGC',
 'Magnitud de reconciliación positiva para plantas que prestan servicio de AGC',
 'Magnitud energía en bolsa internacional a cargo',
 'Magnitud energía en bolsa nacional a cargo',
 'Magnitud responsabilidad comercial AGC',
 'Magnitud ventas en bolsa internacional en energía',
 'Magnitud ventas en bolsa nacional en energía',
 'Magnitud ventas transacciones en bolsa en energía',
 'Meteorología local en Plantas Eólicas',
 'Meteorología local en Plantas Solares',
 'Montos de garantías para cubrir las transacciones en el mercado de energía mayorista',
 'Montos de garantías para cubrir las transacciones en el mercado de energía mayorista agregados',
 'Montos de garantías y mecanismos alternativos para cubrir las transacciones en el mercado de energía mayorista',
 'Montos de garantías y mecanismos alternativos para cubrir las transacciones en el mercado de energía mayorista agregados',
 'Montos por indisponibilidad de las líneas de transmisión nacional y regional del SIN en COP',
 'Máximo precio ofertado',
 'Nivel de Probabilidad de Vertimiento',
 'Nivel de embalse declarado por el agente diariamente',
 'Nivel embalse reportado menos compromisos EVE embalsados por planta',
 'Niveles Mínimos Operativos de Embalses de invierno',
 'Niveles Mínimos Operativos de Embalses de verano',
 'Número de intentos para cumplir pruebas de disponiblidad',
 'Obligación de energía firme por submercado',
 'Oportunidad en el reporte de información por parte de XM, el Administrador del SIMEM y otros',
 'Oportunidad en la entrega de información por parte de los agentes de contratos largo plazo',
 'Otros costos variables asociados al SIN',
 'Otros costos variables hidráulicos y térmicos',
 'Panorama energético Corto Plazo Embalse',
 'Panorama energético Corto Plazo Supuestos y Resultados',
 'Participación en Convocatorias de Participación en Subasta de Cierre de agentes registrados',
 'Parámetros técnicos de las líneas de transmisión',
 'Parámetros técnicos de las plantas de generación',
 'Porcentaje Estimado de cobertura con contratos entre agentes',
 'Porcentaje estimado de cobertura con contratos de convocatorias del SICEP para el mercado regulado',
 'Potencia asociada con la holgura',
 'Precio de Oferta Declarado',
 'Precio de Oferta de Arranque y Parada por recurso USD',
 'Precio de Transacciones en Bolsa',
 'Precio de bolsa horario',
 'Precio de bolsa ponderado',
 'Precio de cierre de los mecanismos de asignación de OEF',
 'Precio de escasez ponderado',
 'Precio de oferta de la planta en el proceso del despacho ideal, en COP/kWh',
 'Precio de oferta de la planta para cada configuración ofertada en el proceso del despacho ideal, en COP/kWh',
 'Precio de oferta en el nodo frontera para exportación',
 'Precio oferta arranque y parada por unidad para el combustible USD',
 'Precios de escasez del Cargo por Confiabilidad',
 'Precios de escasez promedio ponderado por agente',
 'Precios futuros horarios mensuales de contratos con UNR para el total del SIN',
 'Precios futuros horarios mensuales de contratos con UNR por mercado de comercialización',
 'Precios futuros mensuales de contratos con UNR para el total del SIN',
 'Precios futuros mensuales de contratos con UNR por mercado de comercialización',
 'Precios futuros y estadísticas de los contratos de convocatorias del SICEP para el mercado regulado',
 'Precios futuros y estadísticas de los contratos de convocatorias del SICEP para el mercado regulado por comercializador',
 'Precios futuros y estadísticas de los contratos entre agentes',
 'Precios futuros y estadísticas de los contratos entre agentes por comercializador y generador',
 'Precios horarios futuros y estadísticas de los contratos de convocatorias del SICEP para el mercado regulado',
 'Precios horarios futuros y estadísticas de los contratos de convocatorias del SICEP para el mercado regulado por comercializador',
 'Precios horarios futuros y estadísticas de los contratos entre agentes',
 'Precios horarios futuros y estadísticas de los contratos entre agentes por comercializador y generador',
 'Precios horarios y estadísticas de los contratos de convocatorias del SICEP para el mercado regulado',
 'Precios horarios y estadísticas de los contratos de convocatorias del SICEP para el mercado regulado por comercializador',
 'Precios horarios y estadísticas de los contratos entre agentes',
 'Precios horarios y estadísticas de los contratos entre agentes por comercializador',
 'Precios horarios y estadísticas de los contratos entre agentes por generador',
 'Precios promedios horarios mensuales de contratos con UNR para el total del SIN',
 'Precios promedios horarios mensuales de contratos con UNR por mercado de comercialización',
 'Precios promedios horarios mensuales por comercializador de contratos con UNR para el total del SIN',
 'Precios promedios horarios mensuales por comercializador y mercado de comercialización de contratos con UNR',
 'Precios promedios mensuales de contratos con UNR para el total del SIN',
 'Precios promedios mensuales de contratos con UNR por mercado de comercialización',
 'Precios y Energía de los contratos no realizados a través del SICEP con destino al mercado regulado',
 'Precios y Energía de los contratos no realizados a través del SICEP que atienden el mercado de usuarios regulados',
 'Precios y estadísticas de los contratos de convocatorias del SICEP entre agentes integrados verticalmente para el mercado regulado',
 'Precios y estadísticas de los contratos de convocatorias del SICEP entre agentes integrados verticalmente para el mercado regulado por comercializador',
 'Precios y estadísticas de los contratos de convocatorias del SICEP para el mercado regulado, por año de suscripción',
 'Precios y estadísticas de los contratos de convocatorias del SICEP para el mercado regulado, por año de suscripción y por comercializador',
 'Precios y estadísticas de los contratos entre agentes integrados verticalmente para el mercado no regulado',
 'Precios y estadísticas de los contratos entre agentes integrados verticalmente por comercializador',
 'Precios y estadísticas de los contratos entre agentes integrados verticalmente por generador',
 'Precios y estadísticas de los contratos entre agentes, agrupados por año de suscripción',
 'Precios y estadísticas de los contratos entre agentes, por año de suscripción y por comercializador',
 'Precios y estadísticas de los contratos entre agentes, por año de suscripción y por generador',
 'Precios y estadísticas mensuales de contratos de convocatorias del SICEP para el mercado regulado por comercializador',
 'Precios y estadísticas mensuales de contratos entre agentes',

In [24]:
nombre = "Precios y estadísticas mensuales de contratos entre agentes"
df_cat[df_cat["nombreConjuntoDatos"] == nombre]

,idDataset,nombreConjuntoDatos,fechaPublicacion,fechaActualizacion,inicioDato,finDato,fechaDescarga,urlConexionAPI,urlConjuntoDatos,tipoPublicacion
212,bb4a0a,Precios y estadísticas mensuales de contratos ...,2023-09-30T11:11:22.53,2026-02-21T13:30:27.877,2013-01-01T00:00:00,2026-01-01T00:00:00,2025-03-27T08:32:39.95,https://www.simem.coPublicData?startDate=2026-...,https://www.simem.co/datadetail/bb4a0a35-deea-...,Público

In [26]:
# Descargar
nombre = "Precios horarios y estadísticas de los contratos entre agentes"
id_dataset = df_cat[df_cat["nombreConjuntoDatos"] == nombre]["idDataset"].values[0]
fecha_inicio_str = "2026-02-01"
fecha_inicio = dt.datetime.strptime(fecha_inicio_str, "%Y-%m-%d")
fecha_fin_str = "2026-02-28"
fecha_fin = dt.datetime.strptime(fecha_fin_str, "%Y-%m-%d")
list_df = []
keep = True

print(f"Iniciando descarga del dataset '{nombre}', id {id_dataset}")
while keep:
        fecha_part = dt.datetime(fecha_inicio.year, 12, 31)
        fecha_part_str = dt.datetime.strftime(fecha_part, "%Y-%m-%d")
        print(f"{fecha_inicio_str} a {fecha_part_str}")
        if fecha_part >= fecha_fin:
            reader = ReadSIMEM(id_dataset, fecha_inicio_str, fecha_fin_str)
            keep = False
        else:
            reader = ReadSIMEM(id_dataset, fecha_inicio_str, fecha_part_str)
        
        df = reader.main(filter=False)
        list_df.append(df)
        del df

        fecha_inicio = dt.datetime(fecha_inicio.year + 1, 1, 1)
        fecha_inicio_str = dt.datetime.strftime(fecha_inicio, "%Y-%m-%d")

df = pd.concat(list_df)
df.head()

Iniciando descarga del dataset 'Precios horarios y estadísticas de los contratos entre agentes', id 5f246a
2026-02-01 a 2026-12-31
****************************************************************************************************
Initializing object
The object has been initialized with the dataset: "Precios horarios y estadísticas de los contratos entre agentes"
****************************************************************************************************
Inicio consulta sincronica
Creacion url: 0.00027298927307128906
For the URL: https://www.simem.co/backend-files/api/PublicData?startdate=2026-02-01&enddate=2026-02-28&datasetId=5f246a
There are 0 records
Extraccion de registros: 2.6606509685516357
End of data extracting process
****************************************************************************************************

Empty DataFrame
Columns: []
Index: []

In [21]:
df

Empty DataFrame
Columns: []
Index: []